name: Publish to AUR

on:
  push:
    branches:
      - main
      - alpha
  workflow_call:
    inputs:
      version:
        type: string
        description: "Release version"
        required: true
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Release version"
        required: true

jobs:
  release-aur:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Publish to AUR
        run: pnpm publish:aur --version ${{ inputs.version }}
        env:
          AUR_SSH_KEY: ${{ secrets.AUR_SSH_KEY }}
